[tool.mypy]
python_version = "3.8"
strict = true
files = "."
mypy_path = "$MYPY_CONFIG_FILE_DIR/typings"

[[tool.mypy.overrides]]
module = "cattrs"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sortedcollections"
ignore_missing_imports = true
