# SPDX-FileCopyrightText: 2022 Calvin Walton
#
# SPDX-License-Identifier: CC0-1.0

name: Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - debian
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - debian

jobs:
  test:
    name: Code formatting, typechecking, and tests
    runs-on: ubuntu-latest
    permissions:
      checks: write

    strategy:
      matrix:
        python-version: [ "3.8" ]
        include:
          - python-version: "3.8"
            ubuntu-codename: "focal"
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install build-essential libgirepository1.0-dev gir1.2-glib-2.0 gir1.2-poppler-0.18 gir1.2-gtk-3.0 gir1.2-gdkpixbuf-2.0 gir1.2-pango-1.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            setup.cfg
            requirements-dev.txt
            constraints-*.txt

      - name: Install package and dependencies
        run: |
          pip install -r requirements-dev.txt -c constraints-ubuntu-${{ matrix.ubuntu-codename }}.txt
          pip install -e . -c constraints-ubuntu-${{ matrix.ubuntu-codename }}.txt

      - name: Check formatting with black
        if: ${{ matrix.python-version == '3.8' }}
        continue-on-error: true
        run: black --check .

      - name: Check types with mypy
        continue-on-error: true
        if: ${{ matrix.python-version == '3.8' }}
        run: mypy

      - name: Test with pytest
        continue-on-error: true
        run: pytest --junitxml=junit/test-results.xml

      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: junit/test-results.xml
