name: Tests Report

on:
  workflow_run:
    workflows: [ Tests ]
    types: [ completed ]

permissions:
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Download test results
        uses: dawidd6/action-download-artifact@v2
        with:
          name: junit
          path: junit/
          workflow: ${{ github.event.workflow.id }}
          workflow_conslusion: ""
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: junit/**.xml
